former

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,16 @@ jobs:
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
+
+    - name: Check ECR Login Status
+      run: |
+         aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <your-ecr-url>
+         if [ $? -eq 0 ]; then
+         echo "ECR login successful"
+         else
+         echo "ECR login failed"
+         exit 1
+         fi  
  
 
     - name: Build, tag, and push docker image to Amazon ECR
